# Generated by Django 4.0.7 on 2023-11-25 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admin_model',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=40)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=40)),
                ('phone', models.CharField(max_length=16)),
            ],
            options={
                'db_table': 'admin',
            },
        ),
        migrations.CreateModel(
            name='Bid_model',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('USERid', models.IntegerField()),
                ('STOCKid', models.IntegerField()),
            ],
            options={
                'db_table': 'bid',
            },
        ),
        migrations.CreateModel(
            name='Stock_model',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=40)),
                ('last', models.FloatField()),
                ('high', models.FloatField()),
                ('low', models.FloatField()),
                ('change_price', models.FloatField()),
                ('changePercent', models.FloatField()),
                ('vol', models.IntegerField()),
                ('change_time', models.TimeField()),
                ('change_date', models.DateField()),
                ('details', models.TextField()),
            ],
            options={
                'db_table': 'stock',
            },
        ),
        migrations.CreateModel(
            name='User_model',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=40)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=40)),
                ('phone', models.CharField(max_length=16)),
                ('dob', models.DateField()),
                ('profession', models.CharField(max_length=40)),
                ('address', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'user',
            },
        ),
    ]
